### ISSUE TITLE
Support merging multiple ranges into a single scale

### ISSUE THREAD

**Issue by ericsoco** [vega/vega-scale#8]
I have multiple ordinal scales in my spec, and need to merge them into a single ordinal scale for use with my legend and tooltip.

```
{
  "name": "color_0_0",
  "type": "ordinal",
  "domain": {"data": "output_0_0", "field": "city"},
  "range": ["#88572C", "#FF991F", "#DDB27C", "#11939a"]
},
{
  "name": "color_0_1",
  "type": "ordinal",
  "domain": {"data": "output_0_1", "field": "country"},
  "range": ["#DA70BF", "#F15C17"]
}
```

Multi-field data refs work to merge domains, but there doesn't seem to be a way to do the same to merge ranges. The following correctly merges domains, but I can't find a valid syntax to do the same for ranges:

```
{
  "name": "color_0_ordinal",
  "type": "ordinal",
  "domain": {
    "fields": [
      {"signal": "domain('color_0_0')"},
      {"signal": "domain('color_0_1')"}
    ]
  },
  "range": [
    {"signal": "range('color_0_0')"},
    {"signal": "range('color_0_1')"}
  ]
}
```

**Comment by jheer** [comment]
This is not a particularly well-defined operation: even if supported by Vega, there is no guarantee that the domain and range values will pair in a way that matches the two other scales. It would totally depend on the domain sort order, which is flexible.

Also, it seems that multi-source range would only make sense for ordinal scales (unless one would "union" pixel ranges for x,y scales?). All in all, I'm hesitant to consider this as a new feature. If necessary, adding a `concat` expression function to join arrays together would be enough to make your current approach work.

That said, ordinal scale ranges *do* support drawing from data field values much like scale domains.  So if you wanted to aggregate or union values in a data source, you could use that to drive a combined scale range. However, the initial matching problem above may still apply.

From https://vega.github.io/vega/docs/scales/#scale-ranges: For ordinal scales only, a data reference for a set of distinct field values. For example, {"data": "table", "field": "value"}.

**Comment by ericsoco** [comment]
Right, makes sense. I'm only thinking about ordinal scales here. I handle the sorting order with a `'collect'` transform to order keys, and then ensure my corresponding range values are ordered according to that (I'm pulling from a key:color map to generate my spec, but don't trust it fully and therefore rely on data refs for the domain instead of an array literal).

My ranges are array literals (mapped by the user via a UI), so data refs for the ranges don't really work for my use case. Anyway, thanks for the suggestions.
